# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
classes :
  - wso2am
wso2::service_name: wso2am

wso2::hostname : "%{hiera('wso2::ipaddress')}"
wso2::mgt_hostname : am.wso2.com

wso2::template_list :
  - repository/conf/api-manager.xml

wso2::apim_gateway :
    host : gateway.mgt.am.wso2.com
    port : 9443
    api_endpoint_port : 8280
    secure_api_endpoint_port : 8243
    username : admin
    password : admin

wso2::apim_store :
    host : store.am.wso2.com
    port : 9443

wso2::apim_publisher :
    host : publisher.am.wso2.com
    port : 9443

# Clustering configuration
wso2::clustering :
    enabled : true
    membership_scheme : wka
    domain : wso2.am.domain
    local_member_host : "%{hiera('wso2::ipaddress')}"
    local_member_port : 4000
    sub_domain : mgt
    wka :
       members :
         -
           hostname : gateway1.am.wso2.com
           port : 4000
         -
           hostname : publisher1.am.wso2.com
           port : 4000
         -
           hostname : publisher2.am.wso2.com
           port : 4000
         -
           hostname : store1.am.wso2.com
           port : 4000
         -
           hostname : store2.am.wso2.com
           port : 4000


# Datasource configs
#wso2::am_datasources : []
wso2::master_datasources :
  wso2am_db :
    name : WSO2AM_DB
    description : The datasource used for API Manager database
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://apimgtdb.mysql-wso2.com:3306/apimgtdb?autoReconnect=true
    username : "%{hiera('wso2::datasources::common::mysql_username')}"
    password : "%{hiera('wso2::datasources::common::mysql_password')}"
    #secret_alias :
    jndi_config : jdbc/WSO2AM_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_carbon_db :
    name : WSO2_CARBON_DB
    description : The datasource used for local registry
    driver_class_name : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : "%{hiera('wso2::datasources::common::username')}"
    password : "%{hiera('wso2::datasources::common::password')}"
    #secretAlias :
    jndi_config : jdbc/WSO2CarbonDB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_config_db :
    name : WSO2CONFIG_DB
    description : The datasource used for config registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://configdb.mysql-wso2.com:3306/configdb?autoReconnect=true
    username : "%{hiera('wso2::datasources::common::mysql_username')}"
    password : "%{hiera('wso2::datasources::common::mysql_password')}"
    #secret_alias :
    jndi_config : jdbc/WSO2CONFIG_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_gov_db :
    name : WSO2GOV_DB
    description : The datasource used for gov registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://govdb.mysql-wso2.com:3306/govdb?autoReconnect=true
    username : "%{hiera('wso2::datasources::common::mysql_username')}"
    password : "%{hiera('wso2::datasources::common::mysql_password')}"
    #secretAlias :
    jndi_config : jdbc/WSO2GOV_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"


wso2::datasources::common::mysql_username : 'root'
wso2::datasources::common::mysql_password : 'root'

# Registry mounting
wso2::registry_mounts:
  wso2_config_db:
    path: /_system/config
    target_path: /_system/config/apim
    read_only: false
    registry_root: /
    enable_cache: true

  wso2_gov_db:
    path: /_system/gov
    target_path: /_system/gov
    read_only: false
    registry_root: /
    enable_cache: true


# User management configurations
# User store configs
wso2::usermgt :
    add_admin_user : false
    admin_username : networkerauth
    admin_password : REPLACEME
    type : ldap
    connection_url : ldap://rhqipa01.sciquest.com:389
    connection_name : uid=vcenter_ro,cn=users,cn=accounts,dc=ipa,dc=sciquest,dc=com
    connection_password : REPLACEME
    user_search_base : cn=users,cn=accounts,dc=ipa,dc=sciquest,dc=com
    group_search_base : cn=groups,cn=accounts,dc=ipa,dc=sciquest,dc=com

## XXX Specific Custom changes
wso2::template_list :
  - repository/deployment/server/jaggeryapps/store/site/conf/site.json
  - repository/deployment/server/synapse-configs/default/api/_TokenAPI_.xml
  - repository/resources/api_templates/velocity_template.xml

wso2::file_list :
  - repository/components/lib/oauth-app-registration-1.0.0.jar
  - repository/components/lib/jwt-custom-claims-1.0.0.jar
  - repository/components/lib/gateway.client-1.0.0.jar
  - repository/deployment/server/webapps/api-import-export-v1.0.1.war
  - repository/deployment/server/webapps/api#am#publisher#v0.9.war

wso2::third_party_keymanager :
  enabled : true
  client_impl : org.wso2.carbon.apimgt.sciquest.keymanager.APIManagerOAuthClient
  intropection_url : http://127.0.0.1:8080/v1/tokeninfo
  token_url : http://localhost:8080/oauth2/token
  consumer_key : 6b4d6f28-3375-488d-8afa-9187f2c4241f
  consumer_secret_key : 422dfb59-f0c5-452c-849e-576045a7d96f

wso2::map_existing_auth_apps  :
  enabled : true

wso2::jwt_token_generator :
  enabled : true
  jwt_token_generator_impl :  org.wso2.carbon.apimgt.sciquest.jwt.claims.CustomJWTGenerator

wso2::add_concurrent_throttle_handler :
  enabled : true

wso2::api_export_import :
  enabled : true
  backend_api_host_ip : 192.168.69.117
  backend_api_port  : 8080


